routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('pages.welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
// Route::get('/principale', 'PrincipaleController@principale')->name('principale');
Route::get('/nouveau-chantier', 'HomeController@new_site')->name('principale');

    //*************************** */
    //    NEW SITE                //
    //*************************** */

Route::resource('/nouveau-chantier/parametre', 'NewSiteSetController');

Route::resource('/nouveau-chantier/ouvriers', 'NewSiteBobController');

Route::resource('/nouveau-chantier/machines', 'NewSiteMachineController');

Route::resource('/nouveau-chantier/invitations', 'NewSiteInvitationController');

    //*************************** */
    //    PDF JOURNALIER          //
    //*************************** */

Route::resource('/fiche-journaliere', 'FicheJournaliereController');

Route::resource('/pdf-fiche-journaliere', 'PdfJournaliereController');

app/Http/Controllers/NewSiteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class NewSiteController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('new_site.new_site');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/new_site/bob/bob_create.blade.php
@extends('layouts.app')

{{--  Validation client --}}
@section('stylesheet')

    <link href="{{ asset('css/parsley.css') }}" rel="stylesheet">

@endsection


@section('content')

<div class="container-fluid">
@include('partials.new_site._new_site_nav')
<section class="">
    <div class="row"> 
        <div class="col">
            <div class="card content">
                 @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="card-header">
                    <h5 class="text-center">Ajouter un ouvrier</h5>
                </div>
                <form method="POST" action="{{ route('ouvriers.store' )}}" data-parsley-validate="">
                <input type="hidden" name="user_id" value="{{Auth::user()->id}}">
                @csrf
                <div class="card-body">
                    <div class="form-group row">
                        <label for="metier_ouvrier" class="col-sm-3 col-form-label">Métier</label>
                        <div class="col-sm-9">
                        <input type="text" class="form-control" id="metier_ouvrier" name="metier_ouvrier" placeholder="Obligatoire" required="">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="employeur_ouvrier" class="col-sm-3 col-form-label">Employeur</label>
                        <div class="col-sm-9">
                        <input type="text" class="form-control" id="employeur_ouvrier" name="employeur_ouvrier">
                        </div>
                    </div>
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="sous_traitant_ouvrier" value=1 name="sous_traitant_ouvrier">
                        <label class="custom-control-label" for="sous_traitant_ouvrier">Sous-traitant</label>
                    </div>
                </div>    
                <div class="card-footer">
                    <div class="form-group row">
                    <button type="submit" class="col-sm-8 offset-sm-2 btn btn-success btn-block btn-sub">Ajouter</button>  
                    </div>
                </div>
                </form>
            </div>
        </div>
    </div>
</section>
  
</div>
@endsection

{{--  Validation client, Date  --}}
@section('scripts')

<script src="{{ asset('js/parsley.js') }}"></script>

@endsection

resources/views/new_site/bob/bob_edit.blade.php
@extends('layouts.app')

{{--  Validation client --}}
@section('stylesheet')

    <link href="{{ asset('css/parsley.css') }}" rel="stylesheet">

@endsection



@section('content')


<div class="container-fluid">
@include('partials.new_site._new_site_nav')
<section class="main-center">
    <div class="row"> 
        <div class="col">
            <div class="card content">
                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
                <div class="card-header">
                    <h5 class="text-center">Modifier votre ouvrier</h5>
                </div>
                
            {!! Form::model($bob, ['route' => ['ouvriers.update', $bob->id],'data-parsley-validate'=>'','method'=>'PUT']) !!}  
            <div class="card-body">
                {{Form::label('metier_ouvrier', 'Metier:')}}
                {!!Form::text('metier_ouvrier', null,['class'=>'form-control', 'required'=>'', 'placeholder'=>'Obligatoire'])!!}

                {{Form::label('employeur_ouvrier', 'Employeur:')}}
                {!!Form::text('employeur_ouvrier', null,['class'=>'form-control'])!!}

                {{Form::label('sous_traitant_ouvrier', 'Soutraitant:')}}
                {!!Form::checkbox('sous_traitant_ouvrier', '1',['class'=>'form-control'])!!}
                <hr>
                <a href="{{ route('ouvriers.index', $bob->id )}}" class="btn btn-primary">Annuler</a>
                {!! Form::submit('Sauvegarder les changements', ['class'=>'btn btn-success'] ) !!}
            </div>
            {{Form::close()}}
            </div>
        </div>    
    </div>
</section>
  
</div>
@endsection

{{--  Validation client, Date  --}}
@section('scripts')

<script src="{{ asset('js/parsley.js') }}"></script>

@endsection

resources/views/new_site/bob/bob_index.blade.php
@extends('layouts.app')

{{--  Validation client --}}
@section('stylesheet')

    <link href="{{ asset('css/parsley.css') }}" rel="stylesheet">

@endsection


@section('content')

<div class="container-fluid">
@include('partials.new_site._new_site_nav')
<section class="">
    <div class="row"> 
        <div class="col">
            <div class="card content">
                <div class="card-header">
                <h5 class="text-center">Liste de vos ouvrier</h5>
                <a href="{{route('ouvriers.create')}}" class="btn btn-success btn-add">Ajouter un ouvrier</a>
                @if (session('success'))
                    <div class="alert alert-success">
                        {{ session('success') }}
                    </div>
                @endif
                </div> 
                <table class="table">
                    <thead class="card-title text-center">
                            <th scope="col">Metier</th>
                            <th scope="col">Employeur</th>
                            <th scope="col">Sous-traitant</th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                   
                    <tbody>
                        @if ($bobs->isNotEmpty())
                        @foreach ($bobs as $bob)
                        <tr class="text-center">
                            <td>{{$bob->metier_ouvrier}}</td>
                            <td>{{$bob->employeur_ouvrier}}</td>
                        <td>
                                @if($bob->sous_traitant_ouvrier !== null)
                                Oui
                                @else
                                non
                                @endif
                        </td>
                        <td><a href="{{route('ouvriers.edit', $bob->id)}}" class="btn btn-outline-primary" data-toggle="tooltip" data-placement="bottom" title="Modifier"><i class="fas fa-edit"></i></a></td>
                        <td><a href="{{route('ouvriers.show', $bob->id)}}" class="btn btn-danger"><i class="fas fa-trash"></i></a></td>
                        </tr>
                        @endforeach
                        @else()
                            <h3 class="card-header text-center">Vous n'avez pas d'ouvrier</h3>
                        @endif    
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
  
</div>
@endsection

{{--  Validation client, Date  --}}
@section('scripts')

<script src="{{ asset('js/parsley.js') }}"></script>

@endsection

resources/views/new_site/bob/bob_show.blade.php
@extends('layouts.app')

{{--  Validation client --}}
@section('stylesheet')

    <link href="{{ asset('css/parsley.css') }}" rel="stylesheet">

@endsection


@section('content')

<div class="container-fluid">
@include('partials.new_site._new_site_nav')
<section class="">
    <div class="row"> 
        <div class="col">
               <div class="card content">
                <div class="card-header">
                   
                    <h5 class="text-center">Informations sur votre ouvrier</h5>
                </div>

                @if (session('success'))
                    <div class="alert alert-success">
                        {{ session('success') }}
                    </div>
                @endif
                <div class="card-body">
                    <h5 class="card-title"><strong>Métier: </strong>{{ $bob->metier_ouvrier }}</h5>
                    <h5 class="card-title"><strong>Entreprise: </strong>{{ $bob->employeur_ouvrier }}</h5>
                    @if($bob->sous_traitant_ouvrier)
                    <h5 class="card-title">Sous-traitant</h5>
                    @else
                    <h5 class="card-title">Pas Sous-traitant</h5>
                    @endif
                </div>
                <div class="card-footer text-center">
                    {{-- Buttons action --}}
                    {{Form::open(['route'=> ['ouvriers.destroy', $bob->id], 'method'=>'DELETE'])}}
                    {{Form::button('<i class="far fa-trash-alt"></i>',['type'=>'submit','class'=>'btn btn-danger', 'id'=>'opener'])}}
                    <a href="{{route('ouvriers.create')}}" class="btn btn-success"><i class="far fa-plus-square"></i></a>
                    <a href="{{route('ouvriers.index')}}" class="btn btn-warning"><i class="fas fa-list-ol"></i></a>
                    {{Form::close()}}
                </div>    
               </div>
        </div>
    </div>
</section>
  
</div>
@endsection

{{--  Validation client, Date  --}}
@section('scripts')

<script src="{{ asset('js/parsley.js') }}"></script>

@endsection