routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('pages.welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
// Route::get('/principale', 'PrincipaleController@principale')->name('principale');
Route::get('/nouveau-chantier', 'HomeController@new_site')->name('principale');

    //*************************** */
    //    NEW SITE                //
    //*************************** */

Route::resource('/nouveau-chantier/parametre', 'NewSiteSetController');

Route::resource('/nouveau-chantier/ouvriers', 'NewSiteBobController');

Route::resource('/nouveau-chantier/machines', 'NewSiteMachineController');

Route::resource('/nouveau-chantier/invitations', 'NewSiteInvitationController');

    //*************************** */
    //    PDF JOURNALIER          //
    //*************************** */

Route::resource('/fiche-journaliere', 'FicheJournaliereController');

Route::resource('/pdf-fiche-journaliere', 'PdfJournaliereController');

app/Http/Controllers/NewSiteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class NewSiteController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('new_site.new_site');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/new_site/set/set_create.blade.php
@extends('layouts.app')

{{--  Validation client, Date  --}}
@section('stylesheet')

    <link href="{{ asset('css/parsley.css') }}" rel="stylesheet">
    <link href="{{ asset('css/jquery-ui-theme.css') }}" rel="stylesheet">

@endsection


@section('content')

<div class="container-fluid"> 
@include('partials.new_site._new_site_nav')
<section class="">
    <div class="row">
        <div class="col-md-12">
            <div class="card content">
                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif
                <div class="card-header">
                    <h5 class="text-center">Ajouter des paramètres a votre chantier</h5>
                </div>
                
                <form method="POST" action="{{ route('parametre.store' )}}" data-parsley-validate="">
                @csrf
                <input type="hidden" name="user_id" value="{{Auth::user()->id}}">
                <div class="card-body">
                    <div class="form-group row">
                        <label for="maitre_oeuvre" class="col-md-2 col-form-label">Maître d'oeuvre</label>
                        <div class="col-md-4">
                        <input type="text" name="maitre_oeuvre" class="form-control" required="" id="maitre_oeuvre" placeholder="Obligatoire">                      
                        </div>
                        <label for="maitre_ouvrage" class="col-md-2 col-form-label">Maître d'ouvrage</label>
                        <div class="col-md-4">
                        <input type="text" name="maitre_ouvrage" class="form-control" required="" id="maitre_ouvrage" placeholder="Obligatoire">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="nom_chantier" class="col-md-2 col-form-label">Nom du chantier</label>
                        <div class="col-md-4">
                        <input type="text" name="nom_chantier" class="form-control" required="" id="nom_chantier" placeholder="Obligatoire">                      
                        </div>
                        <label for="num_csc" class="col-md-2 col-form-label">CSC</label>
                        <div class="col-md-4">
                        <input type="text" name="num_csc" class="form-control" required="" id="num_csc" placeholder="Obligatoire">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="rue_chantier" class="col-md-2 col-form-label">Rue</label>
                        <div class="col-md-4">
                        <input type="text" name="rue_chantier" class="form-control" required="" id="rue" placeholder="Obligatoire">
                        </div>
                        <label for="num_rue" class="col-md-2 col-form-label">Numéro</label>
                        <div class="col-md-4">    
                        <input type="text" name="num_rue" class="form-control" id="num_rue">
                        </div>
                    </div>    
                    <div class="form-group row">
                        <label for="code_postal" class="col-md-2 col-form-label">Code Postal</label>
                        <div class="col-md-4">
                        <input type="text" name="code_postal" class="form-control" id="code_postal" required="" placeholder="Obligatoire">
                        </div>
                        <label for="ville" class="col-md-2 col-form-label">Ville</label>
                        <div class="col-md-4">
                        <input type="text" name="ville" class="form-control" id="ville">
                        </div>
                    </div>
                    <div class="form-group row">    
                        <label for="date_debut" class="col-md-2 col-form-label">Date de début</label>
                        <div class="col-md-4">
                        <input type="date" name="date_debut" class="form-control" required="" id="date_debut">
                        </div>
                        <label for="date_fin" class="col-md-2 col-form-label">Date de fin</label>
                        <div class="col-md-4">
                        <input type="date" name="date_fin" class="form-control" required="" id="date_fin"> 
                        </div>
                    </div>
                </div>    
                <div class="card-footer">
                    <div class="form-group row">
                        <button type="submit" class="col-md-4 offset-md-4 btn btn-success btn-block btn-sub">Enregistrer</button>    
                    </div>
                </div>
                </form>  
            </div>
        </div>
    </div>

{{--  Calendrier Datepicker  --}}
    <script type="text/javascript">
        $(function() {
            $( "#datepicker" ).datepicker({
            // changeMonth: true,
            // changeYear: true
            });
        });
    </script>
</section>
  
</div>
@endsection

{{--  Validation client, Date  --}}
@section('scripts')

<script src="{{ asset('js/parsley.js') }}"></script>

<script
			  src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
			  integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
			  crossorigin="anonymous"></script>

@endsection

resources/views/new_site/set/set_edit.blade.php
@extends('layouts.app')

{{--  Validation client --}}
@section('stylesheet')

    <link href="{{ asset('css/parsley.css') }}" rel="stylesheet">
    <link href="{{ asset('css/jquery-ui-theme.css') }}" rel="stylesheet">


@endsection


@section('content')

<div class="container-fluid">
@include('partials.new_site._new_site_nav')
<section class="">
    <div class="row"> 
        <div class="col">
            <div class="card content">
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="card-header">
                    <h5 class="text-center">Modifier les paramètres de votre chantier</h5>
                </div>
                {!! Form::model($set, ['route' => ['parametre.update', $set->id],'data-parsley-validate'=>'','method'=>'PUT']) !!}    
                <div class="card-body">
                    <div class="form-group row">
                    {{Form::label('maitre_oeuvre', 'Maître-oeuvre', ['class'=> 'col-md-2 col-form-label'])}}
                    {{Form::text('maitre_oeuvre', null, ['class'=>'form-control col-md-4', 'required'=>'', 'placeholder'=>'Obligatoire'])}}

                    {{Form::label('maitre_ouvrage', 'Maitre-ouvrage:', ['class'=> 'col-md-2 col-form-label'])}}
                    {{Form::text('maitre_ouvrage', null, ['class'=>'form-control col-md-4', 'required'=>'', 'placeholder'=>'Obligatoire'])}}
                    </div>
                    <div class="form-group row">
                    {{Form::label('nom_chantier', 'Nom du chantier:', ['class'=> 'col-md-2 col-form-label'])}}
                    {{Form::text('nom_chantier', null, ['class'=>'form-control col-md-4', 'required'=>'', 'placeholder'=>'Obligatoire'])}}

                    {{Form::label('num_csc', 'Numéro csc:', ['class' =>'col-md-2 col-form-label'])}}
                    {{Form::text('num_csc', null, ['class'=>'form-control col-md-4', 'required'=>'', 'placeholder'=>'Obligatoire'])}}
                    </div>
                    <div class="form-group row">
                    {{Form::label('rue_chantier', 'Rue du chantier:', ['class'=> 'col-md-2 col-form-label'])}}
                    {{Form::text('rue_chantier', null, ['class'=>'form-control col-md-4', 'required'=>'', 'placeholder'=>'Obligatoire'])}}

                    {{Form::label('num_rue', 'Numéro:', ['class'=> 'col-md-2 col-form-label'])}}
                    {{Form::text('num_rue', null, ['class'=>'form-control col-md-4'])}}
                    </div>
                    <div class="form-group row">
                    {{Form::label('code_postal', 'Code postal:', ['class'=> 'col-md-2 col-form-label'])}}
                    {{Form::number('code_postal', null, ['class'=>'form-control col-md-4'])}}

                    {{Form::label('ville', 'Ville:', ['class'=> 'col-md-2 col-form-label'])}}
                    {{Form::text('ville', null, ['class'=>'form-control col-md-4'])}}
                    </div>
                    <div class="form-group row">
                    {{Form::label('date_debut', 'Date de début:', ['class'=> 'col-md-2 col-form-label'])}}
                    {{Form::date('date_debut', null, ['class'=>'form-control col-md-4', 'required'=>'', 'placeholder'=>'Obligatoire'])}}

                    {{Form::label('date_fin', 'Date de fin:', ['class'=> 'col-md-2 col-form-label'])}}
                    {{Form::date('date_fin', null, ['class'=>'form-control col-md-4', 'required'=>'', 'placeholder'=>'Obligatoire'])}}
                    </div>
                </div>
                <div class="card-footer">
                    <div class="form-group row">
                        <a href="{{ route('parametre.index', $set->id )}}" class="col-md-3 offset-md-2 btn btn-primary btn-sub">Annuler</a>
                        {!! Form::submit('Sauvegarder', ['class' => 'col-md-3 offset-md-2 btn btn-success btn-sub']) !!}
                    </div>
                </div>
                {{Form::close()}}
            </div>
        </div>
    </div>
</section>
  
</div>
@endsection

{{--  Validation client, Date  --}}
@section('scripts')

<script src="{{ asset('js/parsley.js') }}"></script>

@endsection

resources/views/new_site/set/set_index.blade.php
@extends('layouts.app')


@section('content')

<div class="container-fluid">
@include('partials.new_site._new_site_nav')
<section class="">
    <div class="row"> 
        <div class="col">
            <div class="card content">
                <div class="card-header">
                <h5 class="text-center">Liste de vos chantiers</h5>
                <a href="{{route('parametre.create')}}" class="btn btn-success btn-add">Ajouter un chantier</a>
                @if (session('success'))
                    <div class="alert alert-success">
                        {{ session('success') }}
                    </div>
                @endif
                </div>
                <table class="table">
                    <thead class="card-title text-center">
                        <tr>
                        <th scope="col">Chantier</th>
                        <th scope="col"></th>
                        <th scope="col"></th>

                        </tr>
                    </thead>
                    <tbody class="card-body">
                        @if ($sets->isNotEmpty())
                        @foreach ($sets as $set)
                        <tr class="text-center">
                            <td>
                                {{$set->nom_chantier}}
                            </td>
                            <td>
                            <a href="{{route('parametre.edit', $set->id)}}" class="btn btn-outline-primary" data-toggle="tooltip" data-placement="bottom" title="Modifier"><i class="fas fa-edit"></i></a>
                            </td>
                            <td><a href="{{route('parametre.show', $set->id)}}" class="btn btn-danger"><i class="fas fa-trash"></i></a></td>
                        </tr>    
                        @endforeach
                        @else()
                            <h3 class="card-header text-center">Vous n'avez pas de chantier</h3>
                        @endif    
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
  
</div>
@endsection

resources/views/new_site/set/set_show.blade.php
@extends('layouts.app')

{{--  Validation client --}}
@section('stylesheet')

    <link href="{{ asset('css/parsley.css') }}" rel="stylesheet">

@endsection


@section('content')

<div class="container-fluid">
@include('partials.new_site._new_site_nav')
<section class="space-content">
    <div class="row"> 
        <div class="col">
            <div class="card content">
                <div class="card-header">
                    <h5 class="text-center">Informations sur votre chantier</h5>
                @if (session('success'))
                    <div class="alert alert-success">
                        {{ session('success') }}
                    </div>
                @endif
                </div>
                <div class="card-body">
                    <h5 class="card-title"><strong>Maître d'oeuvre: </strong>{{ $set->maitre_oeuvre }}</h5>
                    <h5 class="card-title"><strong>Maître d'ouvrage: </strong>{{ $set->maitre_ouvrage }}</h5>
                    <h5 class="card-title"><strong>Nom: </strong>{{ $set->nom_chantier }}</h5>
                    <h5 class="card-title"><strong>Csc: </strong>{{ $set->num_csc }}</h5>
                    <h5 class="card-title"><strong>Rue: </strong>{{ $set->rue_chantier }}</h5>
                    <h5 class="card-title"><strong>Numéro: </strong>{{ $set->num_rue }}</h5>
                    <h5 class="card-title"><strong>Code postal: </strong>{{ $set->code_postal }}</h5>
                    <h5 class="card-title"><strong>Ville: </strong>{{ $set->ville }}</h5>
                    <h5 class="card-title"><strong>Début le: </strong>{{ date('d-m-y', strtotime($set->date_debut)) }}</h5>
                    <h5 class="card-title"><strong>Fin le: </strong>{{ date('d-m-y', strtotime($set->date_fin))}}</h5>
                </div>
                <div class="card-footer text-center">  
                    {{-- Buttons action --}}
                    {{Form::open(['route'=> ['parametre.destroy', $set->id], 'method'=>'DELETE'])}}
                    {{Form::button('<i class="far fa-trash-alt"></i>',['type'=>'submit','class'=>'btn btn-danger'])}}
                    <a href="{{ route('parametre.create' )}}" class="btn btn-success"><i class="far fa-plus-square"></i></a>
                    <a href="{{route('parametre.index')}}" class="btn btn-warning"><i class="fas fa-list-ol"></i></a>
                    {{Form::close()}}
                </div>
            </div>
        </div>
    </div>
</section>

</div>
@endsection

{{--  Validation client, Date  --}}
@section('scripts')

<script src="{{ asset('js/parsley.js') }}"></script>

@endsection