routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('pages.welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
// Route::get('/principale', 'PrincipaleController@principale')->name('principale');
Route::get('/nouveau-chantier', 'HomeController@new_site')->name('principale');

    //*************************** */
    //    NEW SITE                //
    //*************************** */

Route::resource('/nouveau-chantier/parametre', 'NewSiteSetController');

Route::resource('/nouveau-chantier/ouvriers', 'NewSiteBobController');

Route::resource('/nouveau-chantier/machines', 'NewSiteMachineController');

Route::resource('/nouveau-chantier/invitations', 'NewSiteInvitationController');

    //*************************** */
    //    PDF JOURNALIER          //
    //*************************** */

Route::resource('/fiche-journaliere', 'FicheJournaliereController');

Route::resource('/pdf-fiche-journaliere', 'PdfJournaliereController');

resources/views/pages/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">

                <div class="card-body text-center">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    <p>Féliciation, vous êtes enregistré</p>
                    <a href="{{ route('principale') }}">Retour à Joutra</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/pdf_journalier.blade.php
@extends('layouts.layout_journalier')

@section('content')

<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="page">
                <section class="page-content">
                    <div class="row"> 
                        <div class="col-sm-12 page-title text-center">
                            <h3 class="text-center">Journal de travaux</h3>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6 border border-dark entrepreneur">
                            <div class="row">
                                <blockquote class="col content-entrepreneur blockquote">
                                    <strong>Maître de l'ouvrage:</strong>
                                    <p>{{$site->maitre_ouvrage}}</p>
                                </blockquote>
                            </div>    
                            <div class="row">
                                <blockquote class="col content-entrepreneur blockquote">
                                    <strong>Maître d'oeuvre:</strong>
                                    <p>{{$site->maitre_oeuvre}}</p>
                                </blockquote>
                            </div>  
                        </div>
                        <div class="col-6 border border-dark parametre">
                            <div class="row">
                                <div class="col-6 text-left parametre-pdfjourna">
                                    <address>
                                    <strong>{{$site->nom_chantier}}</strong>
                                    <br>
                                    {{$site->rue_chantier}}, {{$site->num_rue}}
                                    <br>
                                    {{$site->code_postal}}, {{$site->ville}}
                                    </address>
                                </div>
                                <div class="col-6 text-right meteo-pdfjourna">
                                    @if($date == date('Y-m-d') )
                                    <ilayer>
                                        <iframe class="" src="http://www.meteobelgium.be/service/fr/code/index.php?code={{$site->code_postal}}&type=ville"
                                        allowtransparency="true" align="center" frameborder="0" width="170" height="125"
                                        scrolling="no" marginwidth="0" marginheight="0">
                                        <a href="http://www.meteobelgique.be" target="_new">www.meteobelgique.be</a>
                                        </iframe>
                                    </ilayer>
                                    @else
                                        <p class="text-left">Date: </p>
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6 border border-dark ouvrier">
                            <blockquote class="ouvrier-pdfjourna">
                                <strong>Ouvriers présents:</strong>
                                @foreach($ouvriers as $ouvrier)
                                    <p>{{$ouvrier}}</p>
                                @endforeach
                            </blockquote>
                        </div>
                        <div class="col-6 border border-dark travaux">
                            <blockquote class="travaux-pdfjourna">
                            <strong>Travaux éxécuté:</strong>
                                <p>{{$travaux}}</p>
                            </blockquote>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6 border border-dark materiaux">
                            <blockquote class="materiaux-pdfjourna">
                            <strong>Matériaux entré ce jour:</strong>
                                <p>{{$materiaux}}</p>
                            </blockquote>
                        </div>
                        <div class="col-6 border border-dark machine">
                                <blockquote class="materiel-pdfjourna">
                                <strong>Matériels présents:</strong>
                                @foreach($materiels as $materiel)
                                    <p>{{$materiel}}</p>
                                @endforeach
                            </blockquote>
                        </div>
                    </div>    
                    <div class="row">
                        <div class="col-6 border border-dark commentaire">
                            <blockquote class="commentaire-pdfjourna">
                            <strong>Commentaire:</strong>
                                <p>{{$commentaire}}</p>
                            </blockquote>
                        </div>
                        <div class="col-6 border border-dark essais">
                            <blockquote class="essais-pdfjourna">
                            <strong>Essais:</strong>
                                <p>{{$essais}}</p>
                            </blockquote>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6 border border-dark signature">
                            <blockquote class="">
                            <strong>Signature:</strong>
                                
                            </blockquote>
                        </div>
                        <div class="col-6 border border-dark signature">
                            <blockquote class=""">
                            <strong>Taratata:</strong>
                                
                            </blockquote>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-12 text-center">
            <section class="button-pdf">
                <a class="btn btn-primary btn-lg" data-toggle="tooltip" data-placement="bottom" title="Modifier" href="{{route('fiche-journaliere.edit', $site->id)}}" role="button"><i class="fa fa-edit"></i></a>
                <a href="{{route('pdf-fiche-journaliere.create')}}" class="btn btn-success btn-lg" data-toggle="tooltip" data-placement="bottom" title="Imprimer"><i class="fas fa-print"></i></a>
                <a href="#" class="btn btn-warning btn-lg" data-toggle="tooltip" data-placement="bottom" title="Liste des fiches"><i class="fas fa-list-ol"></i></a>

                <a href="{{route('principale')}}" class="btn btn-secondary btn-lg">Accueil</a>
            
            
            
            
            </section>
        </div>
    </div>
</div>

@endsection

resources/views/pages/pdf_journalier2.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Joutra @yield('title')</title>

    <!-- Scripts -->
    <script src="{{ asset('js/jquery.js') }}"></script>
    <script src="{{ asset('js/app.js') }}" defer></script>

    <style>

@page {
            margin-top: 0.3em;
            margin-left: 0.6em;
        }

.page {
    background-color: white;

    margin: 0;
}

.page-title {
    background-color: #c7daea;
    height: 20mm;
    width: 200mm;
    border: 1px solid #000;
    text-align: center;
    position: absolute;
    top: 1mm;
    margin: 3mm;
}

.parametre {
    height: 60mm;
    width: 200mm;
}

.param1{
    top: 27mm;
    left: 10mm;
    position: absolute;
}

.param2{
    top: 27mm;
    left: 80mm;
    position: absolute;
}

.param3{
    top: 27mm;
    left: 140mm;
    position: absolute;
}

.param4{
    top: 65mm;
    left: 3mm;
    height: 34mm;
    width: 94mm;
    position: absolute;
    border: 1px solid #000;
    padding: 3mm;
}

.param5{
    top: 65mm;
    left: 103mm;
    height: 34mm;
    width: 94mm;
    position: absolute;
    border: 1px solid #000;
    padding: 3mm;
}

.travaux{
    top: 105mm;
    left: 3mm;
    width: 94mm;
    height: 39mm;
    position: absolute;
    border: 1px solid #000;
    padding: 3mm;
}

.materiaux{
    top: 105mm;
    left: 103mm;
    width: 94mm;
    height: 69mm;
    position: absolute;
    border: 1px solid #000;
    padding: 3mm;
}

.commentaire{
    top: 150mm;
    left: 3mm;
    width: 94mm;
    height: 84mm;
    position: absolute;
    border: 1px solid #000;
    padding: 3mm;
}

.essais{
    top: 180mm;
    left: 103mm;
    width: 94mm;
    height: 54mm;
    position: absolute;
    border: 1px solid #000;
    padding: 3mm;
}

.signature{
    top: 245mm;
    left: 10mm;
    width: 100mm;
    height: 25mm;
    position: absolute;

}
</style>


</head>
    <body>

    <main>
            <div class="page">
                <div class="page-title">
                    <h3 class="">Journal de travaux</h3>
                </div>
                {{-- parametres du chantier --}}
                <div class="parametre">
                    <div class="param1">
                        <strong>Maître de l'ouvrage:</strong>
                        <p>{{$site->maitre_ouvrage}}</p>

                        <strong>Maître d'oeuvre:</strong>
                        <p>{{$site->maitre_oeuvre}}</p>
                    </div>
                    <div class="param2">
                        <address>
                            <strong>{{$site->nom_chantier}}</strong>
                            <br>
                            {{$site->rue_chantier}}, {{$site->num_rue}}
                            <br>
                            {{$site->code_postal}}, {{$site->ville}}
                        </address>
                    </div>
                    <div class="param3">
                        @if($date == date('Y-m-d') )
                        <ilayer>
                            <iframe class="" src="http://www.meteobelgium.be/service/fr/code/index.php?code={{$site->code_postal}}&type=ville"
                            allowtransparency="true" align="center" frameborder="0" width="170" height="125"
                            scrolling="no" marginwidth="0" marginheight="0">
                            <a href="http://www.meteobelgique.be" target="_new">www.meteobelgique.be</a>
                            </iframe>
                        </ilayer>
                        @else
                            <p class="">Date: </p>
                        @endif
                    </div>
                </div>
                
                {{-- Ouvriers et Machines --}}
                <div class="ouvriermachine">
                    <div class="param4">
                        <strong>Ouvriers présents:</strong>
                        <p>@foreach($ouvriers as $ouvrier)
                            {{$ouvrier}}
                        @endforeach</p>
                    </div>
                    <div class="param5">
                        <strong>Matériels présents:</strong>
                        <p>@foreach($materiels as $materiel)
                            {{$materiel}}
                        @endforeach</p>
                    </div>
                </div>

                {{-- travaux --}}
                <div class="travaux">
                    <strong>Travaux éxécuté:</strong>
                    <p>{{$travaux}}</p>
                </div>

                {{-- materiaux --}}
                <div class="materiaux">
                    <strong>Matériaux entré ce jour:</strong>
                    <p>{{$materiaux}}</p>
                </div>

                {{-- commentaire --}}
                <div class="commentaire">
                    <strong>Commentaire:</strong>
                    <p>{{$commentaire}}</p>
                </div>

                {{-- essais --}}
                <div class="essais">
                    <strong>Essais:</strong>
                    <p>{{$essais}}</p>
                </div>

                {{-- signature --}}
                <div class="signature">
                    <p><strong>Signature:</strong></p>
                        
                </div>

            </div>
    </main>
    </body>
</html>

resources/views/pages/principale.blade.php
@extends('layouts.app')

@section('title', ' | Principale')

@section('content')
@include('partials.new_site._new_site_nav')
<div class="container-fluid">

    <section class="principale">      
    @if ($sets->isNotEmpty())  
    @foreach ($sets as $set)       
        <div class="row">  
            <div class="col-md-12">
                <div class="jumbotron jumb-principale">
                    <h1 class="display-12">{{$set->nom_chantier}}</h1>
                    <p><strong>Maître d'ouvrage: </strong>{{$set->maitre_ouvrage}}</p>
                    <p><strong>Mâitre d'oeuvre: </strong>{{$set->maitre_oeuvre}}</p>
                    <hr class="my-12">
                    <p><strong>Début le: </strong>{{ date('d-m-y', strtotime($set->date_debut)) }}</p>
                    <p><strong>Fin le: </strong>{{ date('d-m-y', strtotime($set->date_fin))}}</p>
                    <p class="lead">
                        <a class="btn btn-primary btn-lg" href="{{route('fiche-journaliere.edit', $set->id)}}" role="button">Journalier</a>
                    </p>
                </div>
            </div>
        </div>    
        @endforeach
    @else
        <div class="col text-center">
            <div class="card">
                <div class="card-header">
                    <h2>Pas de chantier en cours</h2>
                    <a class="btn btn-outline-success text-center" href="{{ route('parametre.create') }}">Ajouter un chantier</a>
                </div>
            </div>
        </div>

    </section>    
    @endif 


</div>
@endsection