routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('pages.welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
// Route::get('/principale', 'PrincipaleController@principale')->name('principale');
Route::get('/nouveau-chantier', 'HomeController@new_site')->name('principale');

    //*************************** */
    //    NEW SITE                //
    //*************************** */

Route::resource('/nouveau-chantier/parametre', 'NewSiteSetController');

Route::resource('/nouveau-chantier/ouvriers', 'NewSiteBobController');

Route::resource('/nouveau-chantier/machines', 'NewSiteMachineController');

Route::resource('/nouveau-chantier/invitations', 'NewSiteInvitationController');

    //*************************** */
    //    PDF JOURNALIER          //
    //*************************** */

Route::resource('/fiche-journaliere', 'FicheJournaliereController');

Route::resource('/pdf-fiche-journaliere', 'PdfJournaliereController');

app/Http/Controllers/NewSiteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class NewSiteController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('new_site.new_site');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/new_site/machine/machine_create.blade.php
@extends('layouts.app')

{{--  Validation client --}}
@section('stylesheet')

    <link href="{{ asset('css/parsley.css') }}" rel="stylesheet">

@endsection

@section('content')

<div class="container-fluid">
                    @include('partials.new_site._new_site_nav')
<section class="">
    <div class="row">
        <div class="col">
            <div class="card content">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="card-header">
                    <h5 class="text-center">Ajouter une nouvelle machine</h5>
                </div>
                <div class="card-body">
                    <form method="POST" action="{{ route('machines.store' )}}" data-parsley-validate="">
                    <input type="hidden" name="user_id" value="{{Auth::user()->id}}">
                    @csrf
                    <div class="form-group row">
                        <label for="type_machine" class="col-sm-3 col-form-label">Type</label>
                        <div class="col-sm-9">
                        <input type="text" class="form-control" id="type_machine" placeholder="Obligatoire" name="type_machine" required="">
                        </div>
                    </div>
                    {{-- <div class="form-group row">    
                        <label for="marque_machine" class="col-sm-3 col-form-label">Marque</label>
                        <div class="col-sm-9">
                        <input type="text" class="form-control" id="marque_machine" name="marque_machine">
                        </div>
                    </div>
                    <div class="form-group row"> 
                        <label for="proprietaire_machine" class="col-sm-3 col-form-label">Propriétaire</label>
                        <div class="col-sm-9">
                        <input type="text" class="form-control" id="proprietaire_machine" name="proprietaire_machine" placeholder="Obligatoire" required="">
                        </div>
                    </div> --}}
                    <div class="form-group row"> 
                        <label for="immatriculation_machine" class="col-sm-3 col-form-label">Immatriculation</label>
                        <div class="col-sm-9">
                        <input type="text" class="form-control" id="immatriculation_machine" name="immatriculation_machine" placeholder="Obligatoire" required="">
                        </div>
                    </div>
                    <div class="custom-control custom-checkbox"> 
                        <input type="checkbox" class="custom-control-input" id="sous_traitant_machine" name="sous_traitant_machine" value="1" name="sous_traitant_machiner">
                        <label class="custom-control-label" for="sous_traitant_machine" >Sous-traitant</label>
                    </div>
                </div>    
                <div class="card-footer">
                    <div class="form-group row"> 
                        <button type="submit" class="col-sm-8 offset-sm-2 btn btn-success btn-block btn-sub">Ajouter</button>  
                    </div>    
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
  
</div>
@endsection

{{--  Validation client, Date  --}}
@section('scripts')

<script src="{{ asset('js/parsley.js') }}"></script>

@endsection

resources/views/new_site/machine/machine_edit.blade.php
@extends('layouts.app')

{{--  Validation client --}}
@section('stylesheet')

    <link href="{{ asset('css/parsley.css') }}" rel="stylesheet">

@endsection


@section('content')

<div class="container-fluid">
@include('partials.new_site._new_site_nav')
<section class="">
    <div class="row"> 
        <div class="col">
            <div class="card content">
                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
                <div class="card-header">
                    <h5 class="text-center">Modifier votre machine</h5>
                </div>
            {!! Form::model($machine, ['route' => ['machines.update', $machine->id],'data-parsley-validate'=>'','method'=>'PUT']) !!} 
            <div class="card-body">
                {{Form::label('type_machine', 'Type:')}}
                {{Form::text('type_machine', null, ['class'=>'form-control', 'required'=>'', 'placeholder'=>'Obligatoire'])}}

                {{Form::label('marque_machine', 'Marque:')}}
                {{Form::text('marque_machine', null, ['class'=>'form-control'])}}

                {{Form::label('proprietaire_machine', 'Proprietaire:')}}
                {{Form::text('proprietaire_machine', null, ['class'=>'form-control', 'required'=>'', 'placeholder'=>'Obligatoire'])}}

                {{Form::label('immatriculation_machine', 'Immatriculation:')}}
                {{Form::text('immatriculation_machine', null, ['class'=>'form-control', 'required'=>'', 'placeholder'=>'Obligatoire'])}}

                {{Form::label('sous_traitant_machine', 'Soutraitant:')}}
                {{Form::checkbox('sous_traitant_machine', '1', ['class'=>'form-control'])}}                
            </div>
            <div class="card-footer">
                <a href="{{ route('machines.index', $machine->id )}}" class="btn btn-primary">Annuler</a>
                {{Form::submit('Sauvegarder les changements', ['class'=>'btn btn-success'])}}
            </div>
            {{Form::close()}}
            </div>
        </div>
    </div>
</section>
  
</div>
@endsection

{{--  Validation client, Date  --}}
@section('scripts')

<script src="{{ asset('js/parsley.js') }}"></script>

@endsection

resources/views/new_site/machine/machine_index.blade.php
@extends('layouts.app')

{{--  Validation client --}}
@section('stylesheet')

    <link href="{{ asset('css/parsley.css') }}" rel="stylesheet">

@endsection


@section('content')

<div class="container-fluid">
@include('partials.new_site._new_site_nav')
<section class="">
    <div class="row"> 
        <div class="col">
                <div class="card content">
                    <div class="card-header">
                    <h5 class="text-center">Liste de vos machines</h5>
                    <a href="{{route('machines.create')}}" class="btn btn-success btn-add">Ajouter une machine</a>
                    @if (session('success'))
                        <div class="alert alert-success">
                            {{ session('success') }}
                        </div>
                    @endif
                    </div>

                    <table class="table">
                        <thead class="card-title text-center">
                            <tr>
                            <th scope="col">Type de machine</th>
                            {{-- <th scope="col">Marque</th>
                            <th scope="col">Proprietaire</th> --}}
                            <th scope="col">Immatriculation</th>
                            <th scope="col">Sous-traitant</th>
                            <th></th>
                            <th></th>
                            </tr>
                        </thead>
                        <tbody class="card-body">
                            @if ($machines->isNotEmpty())
                            @foreach ($machines as $machine)
                            <tr class="text-center">
                                <td>{{$machine->type_machine}}</td>
                                {{-- <td>{{$machine->marque_machine}}</td>
                                <td>{{$machine->proprietaire_machine}}</td> --}}
                                <td>{{$machine->immatriculation_machine}}</td>
                            <td>
                                    @if($machine->sous_traitant_machine !== 0)
                                    Oui
                                    @else
                                    non
                                    @endif
                            </td>
                            <td><a href="{{route('machines.edit', $machine->id)}}" class="btn btn-outline-primary" data-toggle="tooltip" data-placement="bottom" title="Modifier"><i class="fas fa-edit"></i></a></td>
                            <td><a href="{{route('machines.show', $machine->id)}}" class="btn btn-danger"><i class="fas fa-trash"></i></a></td>
                            </tr>
                            @endforeach
                            @else()
                                <h3 class="card-header text-center">Vous n'avez pas de machine créé</h3>
                            @endif
                        </tbody>
                    </table>
                </div>
        </div>
    </div>
</section>
  
</div>
@endsection

{{--  Validation client, Date  --}}
@section('scripts')

<script src="{{ asset('js/parsley.js') }}"></script>

@endsection

resources/views/new_site/machine/machine_show.blade.php
@extends('layouts.app')

{{--  Validation client --}}
@section('stylesheet')

    <link href="{{ asset('css/parsley.css') }}" rel="stylesheet">

@endsection


@section('content')

<div class="container-fluid">
@include('partials.new_site._new_site_nav')
<section class="">
    <div class="row"> 
        <div class="col">
            <div class="card content">
                <div class="card-header">
                    <h5 class="text-center">Informations sur votre machine</h5>
                </div>
                @if (session('success'))
                    <div class="alert alert-success">
                        {{ session('success') }}
                    </div>
                @endif
            <div class="card-body">
                <h5 class="card-title"><strong>Type de machine: </strong>{{ $machine->type_machine }}</h5>
                {{-- <h5 class="card-title"><strong>Marque: </strong>{{ $machine->marque_machine }}</h5>
                <h5 class="card-title"><strong>Proprietaire: </strong>{{ $machine->proprietaire_machine }}</h5> --}}
                <h5 class="card-title"><strong>Immatriculation: </strong>{{ $machine->immatriculation_machine }}</h5>
                @if($machine->sous_traitant_machine)
                <h5 class="card-title">Sous-traitant</h5>
                @else
                <h5 class="card-title">Pas sous-traitant</h5>
                @endif
            </div>
            <div class="card-footer text-center">
                {{-- Buttons action --}}
                {{Form::open(['route'=> ['machines.destroy', $machine->id], 'method'=>'DELETE'])}}
                {{Form::button('<i class="far fa-trash-alt"></i>',['type'=>'submit','class'=>'btn btn-danger'])}}
                <a href="{{ route('machines.create' )}}" class="btn btn-success"><i class="far fa-plus-square"></i></a>
                <a href="{{route('machines.index')}}" class="btn btn-warning"><i class="fas fa-list-ol"></i></a>
                {{Form::close()}}
            </div>
            </div>
        </div>
    </div>
</section>
  
</div>
@endsection

{{--  Validation client, Date  --}}
@section('scripts')

<script src="{{ asset('js/parsley.js') }}"></script>

@endsection